### ISSUE TITLE
Add CockroachDB to list of valid datasource providers

### ISSUE THREAD

**Issue by janpio** [prisma/reflector#8]
#### Perceived Problem

PDP does not work with `provider = cockroachdb` and the matching preview feature, because this library declines it:
https://prisma-company.slack.com/archives/C02K246T9RQ/p1649448161183599?thread_ts=1649447917.280059&cid=C02K246T9RQ

#### Ideas / Proposed Solution(s)

Add `cockroachdb` to the list of allowed provider values in a datasource.

**Comment by jasonkuhrt** [comment]
@janpio label sync is setup for this repo now. I've added this issue to our project too.

**Comment by janpio** [comment]
I actually took a shot at this in pdp-control-plane directly, which currently seems to duplicate a lot of this logic, but got lost in TS types stuff: https://github.com/prisma/pdp-control-plane/pull/2279
